server:
  port: 2333
  address: 127.0.0.1
lavalink:
  server:
    password: "lavalink password"
    ws:
      port: 1337
      host: 127.0.0.1
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    sentryDsn: "sentry dsn"
    stacktrace.app.packages:    
    bufferDurationMs: 400
youtubePlaylistLoadLimit: 600
